node createLongTermTrainingSet.js 1standToTurn\hasc-roki-acc.csv
node createLongTermTrainingSet.js 1standToTurn\hasc-yone-acc.csv
node createLongTermTrainingSet.js 1standToTurn\hasc-yoshi-acc.csv
node createLongTermTrainingSet.js 2sitToLye\hasc-yone-acc.csv
node createLongTermTrainingSet.js 2sitToLye\hasc-yoshi-acc.csv
node createLongTermTrainingSet.js 3walk\hasc-yone-acc.csv
node createLongTermTrainingSet.js 3walk\hasc-yoshi-acc.csv
node createLongTermTrainingSet.js 4run\hasc-yone-acc.csv
node createLongTermTrainingSet.js 4run\hasc-yoshi-acc.csv